# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brian/Documents/Classes/CS378RoboticsLeonettiF14/elevators

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brian/Documents/Classes/CS378RoboticsLeonettiF14/elevators

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brian/Documents/Classes/CS378RoboticsLeonettiF14/elevators/CMakeFiles /home/brian/Documents/Classes/CS378RoboticsLeonettiF14/elevators/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brian/Documents/Classes/CS378RoboticsLeonettiF14/elevators/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build/Project

# Build rule for target.
build/Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build/Project
.PHONY : build/Project

# fast build rule for target.
build/Project/fast:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/build
.PHONY : build/Project/fast

src/CameraInterface.o: src/CameraInterface.cpp.o
.PHONY : src/CameraInterface.o

# target to build an object file
src/CameraInterface.cpp.o:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/CameraInterface.cpp.o
.PHONY : src/CameraInterface.cpp.o

src/CameraInterface.i: src/CameraInterface.cpp.i
.PHONY : src/CameraInterface.i

# target to preprocess a source file
src/CameraInterface.cpp.i:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/CameraInterface.cpp.i
.PHONY : src/CameraInterface.cpp.i

src/CameraInterface.s: src/CameraInterface.cpp.s
.PHONY : src/CameraInterface.s

# target to generate assembly for a file
src/CameraInterface.cpp.s:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/CameraInterface.cpp.s
.PHONY : src/CameraInterface.cpp.s

src/ImageProcessor.o: src/ImageProcessor.cpp.o
.PHONY : src/ImageProcessor.o

# target to build an object file
src/ImageProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/ImageProcessor.cpp.o
.PHONY : src/ImageProcessor.cpp.o

src/ImageProcessor.i: src/ImageProcessor.cpp.i
.PHONY : src/ImageProcessor.i

# target to preprocess a source file
src/ImageProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/ImageProcessor.cpp.i
.PHONY : src/ImageProcessor.cpp.i

src/ImageProcessor.s: src/ImageProcessor.cpp.s
.PHONY : src/ImageProcessor.s

# target to generate assembly for a file
src/ImageProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/ImageProcessor.cpp.s
.PHONY : src/ImageProcessor.cpp.s

src/SoundInterface.o: src/SoundInterface.cpp.o
.PHONY : src/SoundInterface.o

# target to build an object file
src/SoundInterface.cpp.o:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/SoundInterface.cpp.o
.PHONY : src/SoundInterface.cpp.o

src/SoundInterface.i: src/SoundInterface.cpp.i
.PHONY : src/SoundInterface.i

# target to preprocess a source file
src/SoundInterface.cpp.i:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/SoundInterface.cpp.i
.PHONY : src/SoundInterface.cpp.i

src/SoundInterface.s: src/SoundInterface.cpp.s
.PHONY : src/SoundInterface.s

# target to generate assembly for a file
src/SoundInterface.cpp.s:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/SoundInterface.cpp.s
.PHONY : src/SoundInterface.cpp.s

src/SoundProcessor.o: src/SoundProcessor.cpp.o
.PHONY : src/SoundProcessor.o

# target to build an object file
src/SoundProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/SoundProcessor.cpp.o
.PHONY : src/SoundProcessor.cpp.o

src/SoundProcessor.i: src/SoundProcessor.cpp.i
.PHONY : src/SoundProcessor.i

# target to preprocess a source file
src/SoundProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/SoundProcessor.cpp.i
.PHONY : src/SoundProcessor.cpp.i

src/SoundProcessor.s: src/SoundProcessor.cpp.s
.PHONY : src/SoundProcessor.s

# target to generate assembly for a file
src/SoundProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/SoundProcessor.cpp.s
.PHONY : src/SoundProcessor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/build/Project.dir/build.make CMakeFiles/build/Project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... build/Project"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/CameraInterface.o"
	@echo "... src/CameraInterface.i"
	@echo "... src/CameraInterface.s"
	@echo "... src/ImageProcessor.o"
	@echo "... src/ImageProcessor.i"
	@echo "... src/ImageProcessor.s"
	@echo "... src/SoundInterface.o"
	@echo "... src/SoundInterface.i"
	@echo "... src/SoundInterface.s"
	@echo "... src/SoundProcessor.o"
	@echo "... src/SoundProcessor.i"
	@echo "... src/SoundProcessor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

